spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8081
api:
  url: "http://192.168.1.44:1040"
