spring:
  datasource:
    url: jdbc:h2:mem:atom
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8081
api:
  url: "http://192.168.1.44:1040"
  cut-url: "http://192.168.1.44:"
scheduled:
  broken-machines: "25000"
  repairing-machines: "60000"
  new-requests: "30000"
  queue-view: "35000"
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user@gmail.com"
  full-name: "Админ Админович Админов"