spring:
  profiles:
    active: "pg"
server:
  port: 8081
api:
  url: "http://192.168.1.44:1040"
  cut-url: "http://192.168.1.44:"
scheduled:
  broken-machines: "25000"
  update-batch: "20000"
  repairing-machines: "27000"
  new-requests: "30000"
  queue-view: "35000"
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user@gmail.com"
  full-name: "Админ Админович Админов"